import React from 'react';
import { 
  HelpCircle, 
  Book, 
  Zap, 
  Trophy, 
  Settings, 
  ShieldCheck, 
  MessageCircle, 
  Mail, 
  Github, 
  AlertCircle,
  Keyboard,
  MousePointer2,
  Activity,
  ChevronRight
} from 'lucide-react';
import { motion } from 'motion/react';

const HelpView: React.FC = () => {
  const faqs = [
    {
      question: "What is ZippyType?",
      answer: "ZippyType is a professional-grade speed typing platform designed to help you improve your typing speed and accuracy through AI-generated challenges, real-time analytics, and competitive game modes.",
      icon: <Zap className="text-amber-400" size={18} />
    },
    {
      question: "How is WPM calculated?",
      answer: "Words Per Minute (WPM) is calculated by taking the total number of characters typed (including spaces) divided by 5, then divided by the time taken in minutes. This is the industry standard for measuring typing speed.",
      icon: <Activity className="text-emerald-400" size={18} />
    },
    {
      question: "What are the different game modes?",
      answer: "We offer Solo (practice alone), AI Race (compete against bots), and Multiplayer (compete against real players). You can also choose between Classic, Sudden Death (one mistake and you're out), and Power-Up modes.",
      icon: <Trophy className="text-purple-400" size={18} />
    },
    {
      question: "How do I unlock achievements?",
      answer: "Achievements are unlocked by reaching specific milestones like hitting a certain WPM, maintaining high accuracy, or completing a specific number of races. You can view your progress in your Profile.",
      icon: <ShieldCheck className="text-indigo-400" size={18} />
    },
    {
      question: "My keyboard isn't responding correctly?",
      answer: "Ensure your browser focus is on the typing input area. If issues persist, try refreshing the page or checking your keyboard layout settings in the 'Hardware' tab of the Settings menu.",
      icon: <Keyboard className="text-rose-400" size={18} />
    }
  ];

  return (
    <div className="max-w-4xl mx-auto space-y-8 pb-20 animate-in fade-in slide-in-from-bottom-4 duration-700">
      {/* Header */}
      <div className="text-center space-y-4">
        <div className="inline-flex p-4 bg-indigo-500/10 text-indigo-400 rounded-3xl mb-2">
          <HelpCircle size={40} />
        </div>
        <h1 className="text-4xl md:text-5xl font-black tracking-tighter text-white uppercase italic">
          Help & <span className="text-transparent bg-clip-text bg-gradient-to-r from-indigo-400 to-purple-500">Support</span>
        </h1>
        <p className="text-slate-400 font-medium max-w-lg mx-auto">
          Everything you need to know about ZippyType. Can't find what you're looking for? Reach out to our team.
        </p>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
        {/* Core Features */}
        <div className="md:col-span-2 space-y-6">
          <div className="glass rounded-[2rem] p-8 border border-white/10 space-y-6">
            <div className="flex items-center gap-3">
              <Book className="text-indigo-400" size={24} />
              <h2 className="text-xl font-black text-white uppercase tracking-tight">Core Features</h2>
            </div>
            
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
              {[
                { title: "AI Generation", desc: "Dynamic text generated by Gemini AI tailored to your skill level." },
                { title: "Real-time Stats", desc: "Live WPM, accuracy, and error tracking as you type." },
                { title: "Global Leaderboards", desc: "Compete with the best typists around the world." },
                { title: "Custom Themes", desc: "Personalize your experience with vibrant color palettes." }
              ].map((feature, i) => (
                <div key={i} className="p-4 bg-white/5 rounded-2xl border border-white/5 hover:border-white/10 transition-colors">
                  <h3 className="text-sm font-bold text-white mb-1">{feature.title}</h3>
                  <p className="text-xs text-slate-400 leading-relaxed">{feature.desc}</p>
                </div>
              ))}
            </div>
          </div>

          {/* FAQ Accordion-style */}
          <div className="space-y-4">
            <h2 className="text-xs font-black text-slate-500 uppercase tracking-[0.3em] ml-4">Frequently Asked Questions</h2>
            {faqs.map((faq, i) => (
              <motion.div 
                key={i}
                initial={{ opacity: 0, y: 10 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ delay: i * 0.1 }}
                className="glass rounded-2xl p-6 border border-white/5 hover:border-white/10 transition-all group cursor-default"
              >
                <div className="flex items-start gap-4">
                  <div className="p-2 bg-white/5 rounded-lg shrink-0">
                    {faq.icon}
                  </div>
                  <div className="space-y-2">
                    <h3 className="text-sm font-bold text-white group-hover:text-indigo-400 transition-colors">{faq.question}</h3>
                    <p className="text-xs text-slate-400 leading-relaxed">{faq.answer}</p>
                  </div>
                </div>
              </motion.div>
            ))}
          </div>
        </div>

        {/* Sidebar: Support & Troubleshooting */}
        <div className="space-y-6">
          <div className="glass rounded-[2rem] p-8 border border-white/10 space-y-6">
            <div className="flex items-center gap-3">
              <AlertCircle className="text-rose-400" size={24} />
              <h2 className="text-xl font-black text-white uppercase tracking-tight">Troubleshooting</h2>
            </div>
            
            <div className="space-y-4">
              <div className="space-y-2">
                <h3 className="text-[10px] font-black text-slate-500 uppercase tracking-widest">App not loading?</h3>
                <p className="text-xs text-slate-400">Try clearing your browser cache or opening the app in Incognito mode.</p>
              </div>
              <div className="space-y-2">
                <h3 className="text-[10px] font-black text-slate-500 uppercase tracking-widest">Stats not saving?</h3>
                <p className="text-xs text-slate-400">Ensure you are logged in. Guest stats are saved locally and may be lost if you clear your browser data.</p>
              </div>
              <div className="space-y-2">
                <h3 className="text-[10px] font-black text-slate-500 uppercase tracking-widest">Laggy performance?</h3>
                <p className="text-xs text-slate-400">Disable 'Confetti Effects' in Settings {'&gt;'} General to improve performance on older devices.</p>
              </div>
            </div>
          </div>

          <div className="glass rounded-[2rem] p-8 border border-white/10 space-y-6 bg-indigo-600/10">
            <div className="flex items-center gap-3">
              <MessageCircle className="text-indigo-400" size={24} />
              <h2 className="text-xl font-black text-white uppercase tracking-tight">Contact Us</h2>
            </div>
            
            <div className="space-y-4">
              <a 
                href="mailto:support@zippytype.com" 
                className="flex items-center gap-3 p-3 bg-white/5 rounded-xl hover:bg-white/10 transition-all border border-white/5"
              >
                <Mail size={18} className="text-indigo-400" />
                <div className="min-w-0">
                  <p className="text-[10px] font-black text-slate-500 uppercase tracking-widest">Email Support</p>
                  <p className="text-xs text-white truncate">support@zippytype.com</p>
                </div>
              </a>
              
              <a 
                href="https://github.com/zippytype/app/issues" 
                target="_blank"
                rel="noopener noreferrer"
                className="flex items-center gap-3 p-3 bg-white/5 rounded-xl hover:bg-white/10 transition-all border border-white/5"
              >
                <Github size={18} className="text-white" />
                <div className="min-w-0">
                  <p className="text-[10px] font-black text-slate-500 uppercase tracking-widest">Report a Bug</p>
                  <p className="text-xs text-white truncate">GitHub Issues</p>
                </div>
              </a>
            </div>

            <div className="pt-4 border-t border-white/5">
              <p className="text-[10px] text-slate-500 text-center italic">
                Average response time: &lt; 24 hours
              </p>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default HelpView;
